import Link from "next/link";
import { SUPPORT_EMAIL } from "@/lib/support";

export const metadata = {
  title: "Terms of Service — WfloAI",
  description: "The rules for using WfloAI, including what workflows may and may not do."
};

const LAST_UPDATED = "17 September 2026";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mt-10">
      <h2 className="text-lg font-semibold tracking-tight text-gray-900">{title}</h2>
      <div className="mt-3 space-y-3 text-sm leading-6 text-gray-600">{children}</div>
    </section>
  );
}

const prohibited = [
  "Sending spam, bulk unsolicited commercial email, or any message the recipient has not agreed to receive. A workflow that sends mail sends it as you, from your address, and you are responsible for it.",
  "Sending mail that misrepresents who it is from, forges headers, or conceals that it was generated by an automation.",
  "Using credentials you are not authorised to use, or configuring a workflow with credentials belonging to another person or organisation.",
  "Using the HTTP Request step as an open proxy, an anonymiser, or a relay for traffic that is not yours.",
  "Directing the HTTP Request step at a service in a way that violates that service's terms, including scraping a site that prohibits it, or evading its rate limits.",
  "Probing, scanning, or attempting to reach private, internal, or non-public network addresses, or attempting to defeat the protections that prevent it.",
  "Attempting to exceed, evade, or automate around the usage limits applied to your account, or running workflows designed primarily to consume capacity.",
  "Uploading or processing content you have no right to process, including another person's personal data that you have no lawful basis to handle.",
  "Using WfloAI to generate or distribute unlawful content, malware, or material intended to deceive, harass, or defraud.",
  "Reselling access, or operating WfloAI on behalf of third parties who have not accepted these terms."
];

export default function TermsPage() {
  return (
    <div className="mx-auto w-full max-w-3xl px-6 py-12 lg:py-16">
      <h1 className="text-3xl font-semibold tracking-tight text-gray-900">
        Terms of Service
      </h1>
      <p className="mt-2 text-sm text-gray-500">Last updated {LAST_UPDATED}</p>

      <p className="mt-6 text-sm leading-6 text-gray-600">
        These terms govern your use of WfloAI. By signing in, you agree to them. If you do not
        agree, do not use the service.
      </p>

      <Section title="What WfloAI is">
        <p>
          WfloAI is a tool for building automations visually. A workflow you build can call AI
          models, run web searches, read files you upload, send email from a Google account
          you connect, and make HTTP requests to services you specify.
        </p>
        <p>
          Two of these need particular care: a workflow{" "}
          <span className="font-medium text-gray-900">sends mail as you</span>, and a workflow{" "}
          <span className="font-medium text-gray-900">
            points our servers at third-party services of your choosing, using credentials you
            supply
          </span>
          . In both cases the action is yours. WfloAI executes what you built.
        </p>
      </Section>

      <Section title="Your account">
        <p>
          You sign in with a Google account and are responsible for everything done through
          it. Do not share access. Tell us promptly at the address below if you believe your
          account has been used without your permission.
        </p>
        <p>You must be old enough to form a binding contract where you live.</p>
      </Section>

      <Section title="AI-generated output">
        <p className="font-medium text-gray-900">
          WfloAI uses AI models to produce output. That output can be inaccurate, incomplete,
          biased, or entirely fabricated, and it is not reviewed by a person before the next
          step of your workflow acts on it.
        </p>
        <p>
          If a workflow sends that output somewhere — an email, an HTTP request, a file — it
          does so without judging whether the output is correct. You are responsible for
          reviewing what your workflows produce before relying on it, and for the consequences
          of what they send. Do not use WfloAI to make decisions that require professional
          advice, including legal, medical, financial, or employment decisions, without a
          qualified person reviewing the output first.
        </p>
      </Section>

      <Section title="Acceptable use">
        <p>You may not use WfloAI, or build a workflow, to do any of the following.</p>
        <ul className="mt-2 space-y-2">
          {prohibited.map((rule) => (
            <li key={rule} className="flex gap-2.5">
              <span
                aria-hidden="true"
                className="mt-2 h-1 w-1 shrink-0 rounded-full bg-gray-400"
              />
              <span>{rule}</span>
            </li>
          ))}
        </ul>
      </Section>

      <Section title="Usage limits">
        <p>
          Accounts are subject to limits on how often workflows may run, how many AI and
          search calls they may make, how frequently schedules may fire, and how much mail may
          be sent. These limits exist to keep cost and abuse bounded, and they may change.
          When a limit is reached, the affected step stops rather than continuing to spend.
        </p>
      </Section>

      <Section title="Suspension and termination">
        <p>
          We may suspend or terminate an account, disable a schedule, or block a specific
          action, at our discretion and without prior notice, if we believe it breaks these
          terms, threatens the service or other users, or exposes us to legal or financial
          risk. Where it is practical and lawful to do so, we will say why.
        </p>
        <p>
          You may stop using WfloAI at any time. Deleting your account is described in the{" "}
          <Link href="/privacy" className="font-medium text-violet-700 hover:underline">
            Privacy Policy
          </Link>
          .
        </p>
      </Section>

      <Section title="Your content">
        <p>
          You keep ownership of what you put into WfloAI and of what your workflows produce.
          You grant us only the permission needed to run the service for you: to store your
          data, and to transmit it to the services listed in the Privacy Policy when your
          workflow calls them.
        </p>
      </Section>

      <Section title="Third-party services">
        <p>
          WfloAI depends on services operated by others, and your workflows may call services
          you choose. We do not control them, we are not responsible for what they do, and
          your use of them is subject to their own terms. An interruption at one of them can
          interrupt WfloAI.
        </p>
      </Section>

      <Section title="No warranty">
        <p>
          WfloAI is provided as-is and as-available, without warranties of any kind, whether
          express or implied. We do not warrant that it will be uninterrupted or error-free,
          or that any output will be accurate or fit for a particular purpose.
        </p>
      </Section>

      <Section title="Limitation of liability">
        <p>
          To the fullest extent permitted by law, we are not liable for indirect, incidental,
          special, consequential, or exemplary damages, or for lost profits, lost data, or
          business interruption, arising from your use of WfloAI — including anything a
          workflow you built sends, requests, or deletes.
        </p>
      </Section>

      <Section title="Changes">
        <p>
          We may update these terms. If a change is material, the date at the top will change
          and the change will be described here. Continuing to use WfloAI after a change means
          you accept it.
        </p>
      </Section>

      <Section title="Contact">
        <p>
          Send questions about these terms to{" "}
          <a
            href={`mailto:${SUPPORT_EMAIL}`}
            className="font-medium text-violet-700 hover:underline"
          >
            {SUPPORT_EMAIL}
          </a>.
        </p>
      </Section>
    </div>
  );
}
